server:
  port : 8761

eureka:
    client :
      service-url :
        defaultZone: http://localhost:8760/eureka/


spring:
    application:
      name: RESTAURANT-SERVICE
    datasource:
       url: jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true
       username: root
       password: root123
       driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       database-platform: org.hibernate.dialect.MySQL8Dialect

